### ISSUE TITLE
Clearing state on unmount

### ISSUE THREAD

**Issue by patrick-jones** [keajs/kea#88]
I have some keyed components à la the [dynamic counter example](https://kea.js.org/guide/counter-dynamic) in the docs. When the component unmounts, I would like its state to disappear from the redux state tree completely. I am currently calling an action that sets state to null in the `stop` saga, but that leaves a bunch of nulled-out cruft in the state.

In other words, I'm doing this (assuming `foo` is the key to the just unmounted component):
```yaml
scenes:
  myscene:
    foo: null
    bar:
      ding: dong
```

I want this:
```yaml
scenes:
  myscene:
    bar:
      ding: dong
```
I can think of some ways to do this outside of kea (some kind of global unmount logic), but I'm wondering if there is something in kea itself that I'm overlooking.
